# Generated by Django 2.1.7 on 2019-03-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

   initial = True

   dependencies = [
       ('core', '0001_initial'),
   ]

   operations = [
       migrations.CreateModel(
           name='Post',
           fields=[
               ('site_name', models.CharField(max_length=200, default='N/A', help_text='Enter an article link to a vacation destination.')),
               ('destination', models.CharField(max_length=200, default='N/A', help_text='Enter the destination')),
               ('author', models.CharField(max_length=200, default='N/A', help_text='Enter the author of the article.')),
               ('description', models.TextField(max_length=1000, default='N/A', help_text='Enter a description of the article.')),
               ('date_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.Author')),
               ('uRL', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.Author')),
               ('posted_by', models.TextField(max_length=200, default='N/A', help_text='Enter the name of the person who is posting.')),
           ],
       ),
   ]
