# Generated by Django 2.1.7 on 2019-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='N/A', help_text='Enter an article link to a vacation destination.', max_length=200)),
                ('destination', models.CharField(default='N/A', help_text='Enter the destination', max_length=200)),
                ('author', models.CharField(default='N/A', help_text='Enter the author of the article.', max_length=200)),
                ('description', models.TextField(default='N/A', help_text='Enter a description of the article.', max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('uRL', models.TextField(default='N/A', help_text='Enter the URL of the article.', max_length=1000)),
                ('posted_by', models.TextField(default='N/A', help_text='Enter the name of the person who is posting.', max_length=200)),
            ],
        ),
    ]
