# Generated by Django 2.1.7 on 2019-03-21 03:57

from django.db import migrations
from django.conf import settings
import os.path
import csv
from django.core.files import File

def import_initial_posts(apps, schema_editor):
    """
    Read a CSV file full of posts and insert them into the database.
    """
    Post = apps.get_model('core', 'Post')
    Author = apps.get_model('core', 'Author')


    Post.objects.all().delete()
    datapath = os.path.join(settings.BASE_DIR, 'core/voyager_data')
    datafile = os.path.join(datapath, 'initial_posts.csv')
    
    with open(datafile) as file:
        reader = csv.DictReader(file) 
        for row in reader:
            #set post_site_name so that you can only add posts that haven't been added
            post_site_name = row['site_name']
            destination = row['destination']
            
            if Post.objects.filter(site_name=post_site_name, destination=destination).count():
                return
            #if the site_name isn't there, make a new post

            author, _ = Author.objects.get_or_create(name=row['author'])

            post = Post(
                site_name=row['site_name'],
                destination=row['destination'],
                author=author,
                description=row['description'],
                date_added=row['date_added'],
                url=row['url'],
                
            )

            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190321_0345'),
    ]

    operations = [
        migrations.RunPython(import_initial_posts),
    ]
