# Generated by Django 2.1.7 on 2019-03-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190321_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='N/A', max_length=200)),
                ('url', models.TextField(default='N/A', max_length=1000)),
                ('site_name', models.CharField(default='N/A', max_length=200)),
            ],
        ),
    ]
