# Generated by Django 2.1.7 on 2019-03-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20190322_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='N/A', max_length=200)),
                ('url', models.TextField(default='N/A', max_length=1000)),
                ('site_name', models.CharField(default='N/A', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
